version: '3'
services:

  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    image: file-invite/php
    container_name: app_todo_list
    depends_on:
      - db
    restart: unless-stopped
    tty: true
    environment:
      APP_DEBUG: 1
      APP_TIMEZONE: UTC
      LOG_CHANNEL: single
      APP_ENV: development
      APP_KEY: base64:qS1JoSLAELbJS+jrobkLSufg1eIyLZmozWnif07QpzY=
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      DB_CONNECTION: mysql
      DB_HOST: db-mysql
      DB_PORT: 3306
      DB_DATABASE: file_db
      DB_USERNAME: root
      DB_PASSWORD: root
      CACHE_DRIVER: file
      QUEUE_DRIVER: sync
    ports:
      - 7000:80
    volumes:
        - .:/var/www/html
    networks:
      - app-network


  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: file_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./.docker/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./.docker/mysql/backups:/docker-entrypoint-initdb.d
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local